import { ALL_COMPONENT_TYPES, CATEGORY_MAP } from './registry.js';

/**
 * Catalog prompt generator — three tiers for LLM system prompt injection.
 *
 * - minimal  (~800 tokens)  — manifest structure + component names only
 * - default  (~2400 tokens) — key components + state bindings + design tokens
 * - full     (~5000 tokens) — complete component reference from forgeui-llm-instructions.md
 */

export function catalogPrompt(tier: 'minimal' | 'default' | 'full' = 'default'): string {
  switch (tier) {
    case 'minimal': return buildMinimalPrompt();
    case 'default': return buildDefaultPrompt();
    case 'full': return buildFullPrompt();
  }
}

function buildMinimalPrompt(): string {
  const byCat = CATEGORY_MAP;
  const cats = Object.entries(byCat)
    .map(([cat, types]) => `  ${cat}: ${types.join(', ')}`)
    .join('\n');

  return [
    'You can create interactive web applications by generating Forge manifests — declarative JSON that describes UI, data, and behavior. You never write code.',
    '',
    'MANIFEST STRUCTURE:',
    '{',
    '  "manifest": "0.1.0",',
    '  "id": "my-app",',
    '  "root": "root-element-id",',
    '  "state": { "key": "initial value" },',
    '  "elements": {',
    '    "root-element-id": {',
    '      "type": "Stack",',
    '      "props": { "spacing": "md" },',
    '      "children": ["child1", "child2"]',
    '    }',
    '  },',
    '  "actions": { "actionName": { "type": "mutateState", "path": "state/path" } }',
    '}',
    '',
    'ELEMENT FORMAT: { "type": "ComponentName", "props": {}, "children": ["id"] }',
    'Root element is set in "root" field. All elements are a flat map — reference by ID, never nest.',
    '',
    'COMPONENTS (37 types):',
    cats,
    '',
    'STATE BINDINGS:',
    '  $state:path         — reactive value',
    '  $computed:path       — derived from table data',
    '  $item:field          — current item in Repeater',
    '  $form:fieldId        — value from input component',
    '',
    'DESIGN TOKENS:',
    '  Spacing: xs, sm, md, lg, xl',
    '  Colors: primary, secondary, success, warning, error, muted, default',
    '  Sizes: sm, md, lg',
    '  Radius: none, sm, md, lg, full',
    '',
    'Never use raw CSS values, hex colors, or pixel sizes. Always use tokens.',
    '',
    'EXAMPLE:',
    '{',
    '  "manifest": "0.1.0", "id": "hello", "root": "root",',
    '  "elements": {',
    '    "root": { "type": "Card", "props": { "title": "Hello World" }, "children": ["msg", "btn"] },',
    '    "msg": { "type": "Text", "props": { "content": "Welcome to Forge!", "variant": "heading2" } },',
    '    "btn": { "type": "Button", "props": { "label": "Click Me", "action": "greet" } }',
    '  },',
    '  "actions": { "greet": { "type": "setState", "path": "greeting", "value": "Hello!" } }',
    '}',
  ].join('\n');
}

function buildDefaultPrompt(): string {
  return [
    buildMinimalPrompt(),
    '',
    '─────────────────────────────────────────────────────────',
    'DETAILED COMPONENT REFERENCE',
    '─────────────────────────────────────────────────────────',
    '',
    'LAYOUT:',
    '  Stack(spacing, direction: "vertical"|"horizontal", align: "start"|"center"|"end"|"stretch", gap)',
    '  Grid(columns: number|"auto", gap, minChildWidth)',
    '  Card(title?, variant: "default"|"outlined"|"elevated"|"compact", padding)',
    '  Container(maxWidth: "sm"|"md"|"lg"|"xl"|"full", padding)',
    '  Tabs(items: string[], bind: $state:path)',
    '  Accordion(items: [{title, contentId}], multiple?: boolean)',
    '  Divider(direction: "horizontal"|"vertical", spacing)',
    '  Spacer(size)',
    '',
    'CONTENT:',
    '  Text(content: string|$binding, variant: "body"|"heading1"|"heading2"|"heading3"|"caption"|"label"|"code", weight, color, align)',
    '  Image(src, alt, aspectRatio: "auto"|"1:1"|"4:3"|"16:9", fit: "cover"|"contain"|"fill", radius)',
    '  Icon(name, size, color)',
    '  Badge(text|$binding, colorScheme, variant: "solid"|"subtle"|"outline")',
    '  Avatar(src?, name, size)',
    '  EmptyState(title, description, icon?, actionLabel?, action?)',
    '',
    'INPUT:',
    '  TextInput(label, placeholder?, bind: $state:path, multiline?, required?, maxLength?)',
    '  NumberInput(label, bind: $state:path, min?, max?, step?, required?)',
    '  Select(label, options: [{value, label}]|string[], bind: $state:path, placeholder?, required?)',
    '  MultiSelect(label, options: [{value, label}]|string[], bind: $state:path, maxSelections?)',
    '  Checkbox(label, bind: $state:path, description?)',
    '  Toggle(label, bind: $state:path, description?)',
    '  DatePicker(label, bind: $state:path, format: "date"|"datetime"|"time", min?, max?)',
    '  Slider(label, bind: $state:path, min, max, step, showValue?)',
    '  FileUpload(label, accept?, maxSize?, multiple?, bind: $state:path)',
    '',
    'ACTION:',
    '  Button(label, action, variant: "primary"|"secondary"|"danger"|"ghost", size, icon?, disabled?)',
    '  ButtonGroup(direction: "horizontal"|"vertical", spacing)',
    '  Link(label, href, variant: "default"|"subtle"|"bold", external?)',
    '',
    'DATA:',
    '  Table(dataPath, columns: [{key, label, sortable?, format?}], pageSize?, searchable?, emptyMessage?)',
    '  List(dataPath, template: elementId, emptyMessage?, dividers?)',
    '  Chart(variant: "line"|"bar"|"donut"|"area"|"scatter"|"pie", dataPath, xKey?, yKey?, colorScheme?, height?)',
    '  Metric(label, value|$binding, format: "number"|"currency"|"percent", goal?, trend?: "up"|"down"|"flat", prefix?, suffix?)',
    '',
    'FEEDBACK:',
    '  Alert(title, message?, variant: "info"|"success"|"warning"|"error", dismissible?)',
    '  Dialog(title, trigger: elementId, confirmLabel?, cancelLabel?, action?)',
    '  Progress(value|$binding, max, variant: "bar"|"ring", size, label?)',
    '  Toast(message, variant: "info"|"success"|"warning"|"error", duration?)',
    '',
    'NAVIGATION:',
    '  Breadcrumb(items: [{label, view?}])',
    '  Stepper(steps: [{label, description?}], activeStep: $state:path, variant: "horizontal"|"vertical")',
    '',
    'DRAWING:',
    '  Drawing(width, height, shapes: Shape[], viewBox?)',
    '  Shape types: rect, circle, ellipse, line, text, arrow, path, icon, badge',
    '  Shapes use design tokens for fill/stroke. Never raw SVG.',
    '',
    'CONDITIONAL RENDERING:',
    '{ "type": "Alert", "props": { ... }, "visible": { "$when": { "path": "state/path", "gt": 0 } } }',
    'Operators: eq, neq, gt, lt, gte, lte, in, notIn, exists.',
    '',
    'REPEATER PATTERN:',
    '{ "type": "Repeater", "props": { "dataPath": "tableName", "template": "templateElementId" } }',
    'Template element uses $item:field bindings for each row.',
    '',
    'ACTIONS:',
    '  mutateState — append/update/delete rows in a table. Path is the table name.',
    '  setState — set a state value.',
    '  submitForm — collect form inputs and trigger an action.',
    '  navigate — switch views.',
    '',
    'SCHEMA (optional, for persistent data):',
    '{ "version": 1, "tables": { "tableName": { "columns": { "col": { "type": "string|number|boolean" } } } } }',
    '',
    'GUIDELINES:',
    '1. Always use design tokens — never raw CSS, hex colors, or pixel sizes.',
    '2. Use flat element maps — reference children by ID, never nest.',
    '3. Use Repeater for lists — define template once, bind to data.',
    '4. Always handle empty states with EmptyState component.',
    '5. Use conditional visibility for show/hide logic.',
    '6. State paths use "/" separators: "view/active", "goals/calories".',
    '7. Actions are declarative — never write JavaScript.',
    '8. Keep manifests under 100KB.',
  ].join('\n');
}

function buildFullPrompt(): string {
  return [
    buildDefaultPrompt(),
    '',
    '─────────────────────────────────────────────────────────',
    'DATA ACCESS (Reading App Data)',
    '─────────────────────────────────────────────────────────',
    '',
    'Forge apps can optionally allow the LLM to read user data for personalized updates.',
    'This is DISABLED by default. The user must consent at app creation time.',
    '',
    'PERMISSION DECLARATION:',
    '{ "dataAccess": { "enabled": true, "readable": ["table1"], "restricted": ["table2"] } }',
    '  enabled: false (default) — LLM cannot read any app data.',
    '  enabled: true — LLM can read tables in "readable". Tables in "restricted" are never sent.',
    '  Always inform the user: "This app allows the AI to read your [data] for personalized updates."',
    '',
    'READING DATA VIA TOOLS:',
    '',
    'forge_read_app_data — returns raw rows from permitted tables:',
    '  Input: { app_id, tables: ["tableName"], limit: 20, since: "2026-04-01" }',
    '  Output: { schema, data: { tableName: [...rows] }, rowCounts }',
    '',
    'forge_query_app_data — returns aggregated summaries (more token-efficient):',
    '  Input: { app_id, queries: [{ table, aggregate: "count|max|min|avg|trend", groupBy?, column?, where? }] }',
    '  Output: { results: [{ data: {...} }] }',
    '',
    'PREFER forge_query_app_data over forge_read_app_data.',
    'Summaries cost ~50-150 tokens vs. ~2,000+ for raw rows.',
    '',
    'THE DATA INTERACTION LOOP:',
    '1. Read — call forge_query_app_data to understand user data (trends, patterns, gaps)',
    '2. Reason — identify what should change in the app (adjust targets, add alerts, modify plans)',
    '3. Update — call forge_update_app with a manifest patch to modify the app structure',
    '',
    'The LLM updates the MANIFEST (app structure, plans, goals, UI), not the user\'s raw data.',
    'Workout logs, tracked meals, journal entries stay untouched in TinyBase.',
    'The LLM modifies the app AROUND the data.',
    '',
    'Example: the LLM reads that squat weight has plateaued for 3 weeks. It sends a manifest patch',
    'that changes the squat rep scheme from 5×5 to 3×8, adds an Alert saying "Deload week — lighter',
    'weight, more reps," and updates the goal Metric. The user\'s logged workouts are unchanged — only the plan adapts.',
    '',
    '─────────────────────────────────────────────────────────',
    'EXAMPLE — HABIT TRACKER',
    '─────────────────────────────────────────────────────────',
    '',
    '{',
    '  "manifest": "0.1.0",',
    '  "id": "habit-tracker",',
    '  "root": "shell",',
    '  "schema": { "version": 1, "tables": { "habits": { "columns": {',
    '    "name": { "type": "string" },',
    '    "streak": { "type": "number", "default": 0 },',
    '    "done_today": { "type": "boolean", "default": false },',
    '    "icon": { "type": "string", "default": "star" }',
    '  } } } },',
    '  "state": { "view/active": "today" },',
    '  "elements": {',
    '    "shell": { "type": "Container", "props": { "maxWidth": "md", "padding": "lg" }, "children": ["header", "tabs", "content"] },',
    '    "header": { "type": "Stack", "props": { "direction": "horizontal", "align": "center", "spacing": "md" }, "children": ["title", "streak-metric"] },',
    '    "title": { "type": "Text", "props": { "content": "Daily Habits", "variant": "heading1" } },',
    '    "streak-metric": { "type": "Metric", "props": { "label": "Best Streak", "value": "$computed:habits/maxStreak", "format": "number", "suffix": " days" } },',
    '    "tabs": { "type": "Tabs", "props": { "items": ["Today", "All Habits", "Add New"], "bind": "$state:view/active" } },',
    '    "content": { "type": "Stack", "props": { "spacing": "md" }, "children": ["habit-list", "empty"] },',
    '    "habit-list": { "type": "Repeater", "props": { "dataPath": "habits", "template": "habit-row" } },',
    '    "habit-row": { "type": "Card", "props": { "variant": "outlined", "padding": "md" }, "children": ["habit-info", "habit-toggle"] },',
    '    "habit-info": { "type": "Stack", "props": { "direction": "horizontal", "align": "center", "spacing": "sm" }, "children": ["habit-icon", "habit-name", "habit-streak"] },',
    '    "habit-icon": { "type": "Icon", "props": { "name": "$item:icon", "size": "md", "color": "primary" } },',
    '    "habit-name": { "type": "Text", "props": { "content": "$item:name", "weight": "medium" } },',
    '    "habit-streak": { "type": "Badge", "props": { "text": "$item:streak", "colorScheme": "success", "variant": "subtle" } },',
    '    "habit-toggle": { "type": "Toggle", "props": { "label": "Done today", "bind": "$item:done_today" } },',
    '    "empty": { "type": "EmptyState", "props": { "title": "No habits yet", "description": "Add your first habit to start tracking", "icon": "plus-circle", "actionLabel": "Add Habit", "action": "show-add-form" }, "visible": { "$when": { "path": "habits", "eq": [] } } }',
    '  },',
    '  "actions": {',
    '    "toggle-habit": { "type": "mutateState", "path": "habits", "operation": "update", "key": "{{id}}", "data": { "done_today": "{{!done_today}}" } },',
    '    "add-habit": { "type": "mutateState", "path": "habits", "operation": "append", "data": { "name": "$form:habit-name", "icon": "$form:habit-icon", "streak": 0, "done_today": false } },',
    '    "delete-habit": { "type": "mutateState", "path": "habits", "operation": "delete", "key": "{{id}}" },',
    '    "show-add-form": { "type": "setState", "path": "view/active", "value": "Add New" }',
    '  }',
    '}',
    '',
    'For sets of repetitive actions (one per day, one per item, etc.), define a single parameterized action and pass the distinguishing value at dispatch time rather than defining one action per item.',
    '',
    'GUIDELINES:',
    '1. Always use design tokens — never raw CSS, hex colors, or pixel sizes.',
    '2. Keep manifests under ~100KB — if an app needs more, it outgrew Forge.',
    '3. Use flat element maps — reference children by ID, never nest.',
    '4. Data tables use pagination — never dump hundreds of rows; set pageSize on Table.',
    '5. Actions are declarative — never write JavaScript callbacks or event handlers.',
    '6. Shapes in Drawing are data — never write raw SVG markup. Use the shape types.',
    '7. State paths use "/" separators: "view/active", "goals/calories".',
    '8. Prefer Repeater for lists — define template once, bind to data path.',
    '9. Always handle empty states with EmptyState component.',
    '10. Use conditional visibility: "visible": {"$when": {...}} to show/hide elements.',
    '11. Data access is opt-in — set dataAccess.enabled: false (or omit) unless user wants LLM to read data.',
    '12. Prefer query over read — use forge_query_app_data for aggregates instead of forge_read_app_data.',
    '13. Never modify user data directly — read to reason, then update the manifest, not the records.',
  ].join('\n');
}

/**
 * Generate a JSON Schema for Forge manifest validation.
 * Useful for structured output generation by LLMs.
 */
export function catalogToJsonSchema(): { type: string; required: string[]; properties: Record<string, unknown> } {
  return {
    type: 'object',
    required: ['manifest', 'id', 'elements'],
    properties: {
      manifest: { type: 'string', const: '0.1.0' },
      id: { type: 'string', pattern: '^[a-z0-9][a-z0-9-]*$' },
      root: { type: 'string' },
      title: { type: 'string' },
      schema: {
        type: 'object',
        properties: {
          version: { type: 'number' },
          tables: {
            type: 'object',
            additionalProperties: {
              type: 'object',
              properties: {
                columns: {
                  type: 'object',
                  additionalProperties: {
                    type: 'object',
                    properties: {
                      type: { type: 'string', enum: ['string', 'number', 'boolean'] },
                      default: {},
                    },
                    required: ['type'],
                  },
                },
              },
              required: ['columns'],
            },
          },
        },
      },
      state: {
        type: 'object',
        additionalProperties: {},
      },
      elements: {
        type: 'object',
        additionalProperties: {
          type: 'object',
          properties: {
            type: { type: 'string', enum: ALL_COMPONENT_TYPES },
            props: { type: 'object' },
            children: { type: 'array', items: { type: 'string' } },
            visible: {
              type: 'object',
              properties: {
                $when: {
                  type: 'object',
                  properties: {
                    path: { type: 'string' },
                    eq: {},
                    neq: {},
                    gt: { type: 'number' },
                    lt: { type: 'number' },
                    gte: { type: 'number' },
                    lte: { type: 'number' },
                    in: { type: 'array' },
                    notIn: { type: 'array' },
                    exists: { type: 'boolean' },
                  },
                  required: ['path'],
                },
              },
            },
          },
          required: ['type'],
        },
      },
      actions: {
        type: 'object',
        additionalProperties: {
          type: 'object',
          properties: {
            type: { type: 'string', enum: ['mutateState', 'setState', 'navigate', 'submitForm'] },
            path: { type: 'string' },
            value: {},
            operation: { type: 'string', enum: ['append', 'update', 'delete'] },
            data: { type: 'object' },
            key: { type: 'string' },
            formId: { type: 'string' },
            action: { type: 'string' },
          },
          required: ['type'],
        },
      },
      dataAccess: {
        type: 'object',
        properties: {
          enabled: { type: 'boolean', default: false },
          readable: { type: 'array', items: { type: 'string' } },
          restricted: { type: 'array', items: { type: 'string' } },
          summaries: { type: 'boolean', default: false },
        },
      },
      persistState: { type: 'boolean' },
      skipPersistState: { type: 'boolean' },
    },
  };
}
